### ISSUE TITLE
Delete tag (e.g. to rename a tag name since there are no edit function) removes from all related snippets without alert to users

### ISSUE THREAD

**Issue by xvhidevx** [JTostitos/snippets-enhancements-bugs#2]
When I swipe to delete the tag, this affects all snippets that uses this tag.. it will be better to notify the user about this..

**Comment by JTostitos** [comment]
Thanks @xvhidevx for the feedback on this. 

1. The Add/Edit Snippet View will now display a trash can symbol to indicate how to remove a tag/language from the current snippet.
2. When going to the Add Language or Add Tag views, there is no more "None" option since that has been replaced by the trash can symbol on Add/Edit Snippet View.
3. First attempt at deleting a tag/language will result in an alert appearing which indicates deleting it will remove it from all snippets. Second or more attempts will not show the alert. Alert can be shown by pressing the question icon in the top left of view.
4. #1 has been resolved by proving swipeActions on each tag/language.
